# Stuff about range()
start = 0
stop = 3
step = 1
for i in range(stop): #if i indicate only one variable, then python assumes that it is the stop variable. this is the same as for (int i = 0; i < stop; i++) {} in java
    print(i)
for i in range(start, stop): #if i pass only two variables, then python assumes that they are the starting and ending. this is the same as for (int i = start; i < stop; i++) {}
    print(i)
for i in range (start, stop, step): #passing all three variables allows the program to function like a java for loop as so: for (int i = start; i < stop; i+=step)
    print(i)

#Stuff about list
lol = ["apples", "bananas", "trucks", 2, 37.2] #notice how it can store multiple types? lists contain references
lol.append(f"{47}h") #adds the string "47h"
print(lol[5]) #prints out 47h

# Example generated by DeepSeek {
# Before
a = [1, 2, 3]
b = [4, 5, 6]

# After extend
a.extend(b)
print(a)  # [1, 2, 3, 4, 5, 6] }

lol.reverse()
for i in range (len(lol)):
    print(lol[i])

'''
Next:
* Dictionaries
* Recursion
* Two-Pointers
* Sliding Window
* Deque
//Why is this "one day" exercise taking over 5 days 💀😭
'''